trangwebbanhangasp/trangwebbanhangasp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trangwebbanhangasp.Dao;
using trangwebbanhangasp.Models;

namespace trangwebbanhangasp.Controllers
{
	public class HomeController : Controller
	{
		public PartialViewResult Taikhoan()
		{
			return PartialView();
		}

		//GET: Thoat
		public ActionResult Logout()
		{
			Session["Taikhoan"] = null;
			return RedirectToAction("Trangchu", "Trangchu");
		}

		// GET: Giohang
		public ActionResult Giohang()
		{
			return View();
		}
		// GET: Thongtin
		public ActionResult Thongtin()
		{
			return View();
		}
		// GET: Lienhe
		thoitrangnamEntities9 db = new thoitrangnamEntities9();
		[HttpGet]
		public ActionResult Lienhe()
		{
			return View();
		}
		[HttpPost]
		public ActionResult Lienhe(FormCollection f)
		{
			var dao = new UserDao();
			string tentk = f["txtTaiKhoan"].ToString();
			string mk = f.Get("txtMatKhau").ToString();
			phanhoi kh = new phanhoi();
			kh.email = tentk;
			kh.noidung = mk;
			kh.ngaygui = DateTime.Now;
			kh.idstatusgui = 1;
			var result = dao.Insertinphanhoi(kh);
			if (result > 0)
			{
				ViewBag.thanhcong = "Phản hồi đã được gửi, chúng tôi sẽ trả lời cho bạn sớm nhất có thể";
			}
			return View();
		}


		//Get timkiemauto
		public JsonResult GetSearchValue(string search)
		{
			List<SanphamModel> allsearch = db.sanphams.Where(x => x.ten_sp.Contains(search)).Select(x => new SanphamModel
			{
				ten_sp = x.ten_sp,

			}).Distinct().Take(10).ToList();
			return new JsonResult { Data = allsearch, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
		}
		public PartialViewResult Timkiem()
		{
			return PartialView();
		}

		//sua tai khoan

			}
}

trangwebbanhangasp/trangwebbanhangasp/Controllers/ThongtinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trangwebbanhangasp.Dao;
using trangwebbanhangasp.Models;

namespace trangwebbanhangasp.Controllers
{
	public class ThongtinController : Controller
	{
		// GET: Thongtin
		Usermodel thi = new Usermodel();
		thoitrangnamEntities9 db = new thoitrangnamEntities9();
		//Chi tiet user
		public ActionResult Details()
		{
			var session = (user)Session["Taikhoan"];
			user user = db.users.SingleOrDefault(n => n.id_user == session.id_user);
			if (user == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(user);
		}
		//Sua user
		[HttpGet]
		public ActionResult Edit()
		{
			var session = (user)Session["Taikhoan"];
			user user = db.users.SingleOrDefault(n => n.id_user == session.id_user);
			if (user == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(user);
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(user user, FormCollection f)
		{
			var dao = new UserDao();

			user u = db.users.SingleOrDefault(n => n.id_user == user.id_user);
			u.ten_khach_hang = user.ten_khach_hang;
			if (u.pass.Equals(user.pass))
			{
				u.pass = user.pass;
			}
			else
			{
				u.pass = user.pass;
				u.pass = dao.ToMD5(user.pass);

			}
			u.tenuser = user.tenuser;
			u.ngay_sinh = user.ngay_sinh;
			u.mail = user.mail;
			u.sdt = user.sdt;
			u.gioi_tinh = user.gioi_tinh;
			u.dia_chi1 = user.dia_chi1;

			db.SaveChanges();

			return RedirectToAction("Details");
		}
	}

}

trangwebbanhangasp/trangwebbanhangasp/Controllers/TimkiemController.cs
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using trangwebbanhangasp.Models;

namespace trangwebbanhangasp.Controllers
{
    public class TimkiemController : Controller
    {
		thoitrangnamEntities9 db = new thoitrangnamEntities9();
		[HttpPost]
		public ActionResult Trangtimkiem(FormCollection f, int? page)
		{
			string tukhoa = f["txtTimkiem"].ToString();
			List<sanpham> list = db.sanphams.Where(n => n.ten_sp.Contains(tukhoa)).ToList();
			int pagenumber = (page ?? 1);
			int pagesize = 12;
			if (list.Count == 0)
			{
				ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
				return View(db.sanphams.OrderBy(n => n.ten_sp).ToPagedList(pagenumber, pagesize));
			}

			ViewBag.ThongBao = "Đã tìm thấy " + list.Count + " kết quả";
			return View(list.OrderBy(n => n.ten_sp).ToPagedList(pagenumber, pagesize));
		}
		public JsonResult ListName(string tukhoa)
		{
			var data = List(tukhoa);
			return Json(new { data, status = true }, JsonRequestBehavior.AllowGet);
		}
		public List<string> List(string key)
		{
			return db.sanphams.Where(n => n.ten_sp.Contains(key)).Select(n => n.ten_sp).ToList();
		}
	}
}

trangwebbanhangasp/trangwebbanhangasp/Views/Home/Lienhe.cshtml
@{
	ViewBag.Title = "Lienhe";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('../../Asserts/images/Bowen-2017-Fall-Winter-Campaign-004.jpg');margin-top: 20px;height:200px;">
	<h2 class="ltext-105 cl0 txt-center">
		Liên hệ
	</h2>
</section>
<section class="bg0 ">
	<div class="container" style="padding:0 60px;">
		<div class="flex-w flex-tr">
			<div class=" bor10 p-lr-60 p-t-55 p-b-60 p-lr-15-lg w-full-md" style="
    width: 57%;
">

				<h4 class="mtext-105 cl2 txt-center p-b-30" style="font-size:23px;">Hãy gửi phản hồi về cho chúng tôi</h4>
				@if (ViewBag.thanhcong == null)
				{
					@Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "padding-bottom:15px;text-align:center;" })
				}
				else
				{
					<h2 style="padding-bottom: 20px;font-family:robotom; font-size: 15px; text-align: center;color: #0e95e6eb;">@ViewBag.thanhcong</h2>
				}
				@using (Html.BeginForm())
				{

					<div class="bor8 m-b-20 how-pos4-parent">
						<input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" id="txtTaiKhoan" name="txtTaikhoan" placeholder="Email của bạn" style="padding-left:27px;">
					</div>

					<div class="bor8 m-b-30">
						<textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" id="txtMatKhau" name="txtMatKhau" placeholder="Chúng tôi có thể giúp gì cho bạn"></textarea>

					</div>

					if (ViewBag.thanhcong == null)
					{
						<button type="submit" class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">Gửi</button>

					}
					else
					{
						<div class="flex-c-m stext-101 cl2 size-119 bg3 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10" style="
    ">
							<a href="/Trangchu/Trangchu" style="color:white;">Quay trở lại mua sắm</a>
						</div>}
				}
			</div>

			<div class="size-210 bor10 flex-w flex-col-m p-lr-50 p-tb-30 p-lr-15-lg w-full-md" style="width:42%;">
				<div class="flex-w w-full p-b-42" style="

    width: 300px;
    font-size: 14px;
;
">
					<span class="fs-18 cl5 txt-center size-211">
						<span class="lnr lnr-map-marker"></span>
					</span>

					<div class="size-212 p-t-2" style="
">
						<span class="mtext-110 cl2" style="
">Địa chỉ</span>

						<p>35/1c, ấp Bắc Lân, xã Bà Điểm, huyện Hóc Môn, thành phố Hồ Chí Minh</p>
					</div>
				</div>

				<div class="flex-w w-full p-b-42" style="
    width: 300px;
    font-size: 14px;
">
					<span class="fs-18 cl5 txt-center size-211">
						<span class="lnr lnr-phone-handset"></span>
					</span>

					<div class="size-212 p-t-2">
						<span class="mtext-110 cl2">SĐT: </span>
						<span class="mtext-110 cl2" style="color: #717fe0;">0902555577</span>

					</div>
				</div>

				<div class="flex-w w-full" style="
    width: 300px;
    font-size: 14px;
">
					<span class="fs-18 cl5 txt-center size-211">
						<span class="lnr lnr-envelope"></span>
					</span>

					<div class="size-212 p-t-2">
						<span class="mtext-110 cl2">Email liên hệ</span>

						<p class="stext-115 cl1 size-213 p-t-18">
							blizzard@gmail.com
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="size-210 bor10 flex-w flex-col-m p-lr-50 p-tb-30 p-lr-15-lg w-full-md" style="width:99%;">



		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3191.207607989638!2d106.78896371411714!3d10.866932360489747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175276120e747b7%3A0x4621264c786596c7!2zxJDhuqFpIGjhu41jIE7DtG5nIEzDom0!5e1!3m2!1svi!2s!4v1561871502969!5m2!1svi!2s" width="970" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>


		</div>
	</div>
</section>

trangwebbanhangasp/trangwebbanhangasp/Views/Home/Taikhoan.cshtml
@using trangwebbanhangasp.Models;


<div class="menu-desktop">
	<ul class="main-menu">


		<li style="padding-top: 17px;">
			<i class="zmdi zmdi-account-box" style="font-size: 35px;"></i>
			<a class="Danhsachsanpham" href="/Home/Danhsachsanpham"></a>
			<a href="/Views/Home/Danhsachsanpham.cshtml"></a>
			<ul class="sub-menu" style="left: -140px;">
				@{
					var session = (user)Session["Taikhoan"];
				}
				@if (Session["Taikhoan"] == null)
				{
					<li><a href="~/Dangkydangnhap/Dangnhap">Đăng nhập</a></li>
					<li><a href="~/Dangkydangnhap/Dangky">Đăng ký</a></li>
				}
				else
				{
					<li><a href="~/Thongtin/Details">@session.ten_khach_hang</a> </li>
					<li>@Html.ActionLink("Thoát", "Logout", "Home")</li>
				}

			</ul>
		</li>
	</ul>
</div>

trangwebbanhangasp/trangwebbanhangasp/Views/Home/Thongtin.cshtml
@{
    ViewBag.Title = "Thongtin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('../../Asserts/images/quan.jpg');margin-top: 20px;height:200px;">
	<h2 class="ltext-105 cl0 txt-center">Câu chuyện về Blizzard</h2>
</section>
<section class="bg0 p-t-75 p-b-120">
	<div class="container">
		<div class="row p-b-148">
			<div class="col-md-7 col-lg-8">
				<div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
					<h3 class="mtext-111 cl2 p-b-16">Tiếu sử Blizzard</h3>

					<p class="stext-113 cl6 p-b-26" style="
    text-align: justify;
">
						Blizzard là một nhãn hiệu thời trang của Ý chuyên về các sản phẩm cao cấp cho nam và nữ (giày dép, túi xách, phụ kiện thời trang...), nhãn hiệu Prada được thành lập bởi Mario Prada năm 1913.

						Blizzard được xem là một trong những nhà thiết kế có ảnh hưởng nhất trong ngành công nghiệp thời trang.[2] Cũng giống như những thương hiệu thời trang khác, Blizzard phải đấu tranh chống lại hàng nhái và đảm bảo hàng chính hãng từ các cửa hàng chính thức của hãng trên thế giới cũng như những cửa hàng online trên mạng.
					</p>

					<p class="stext-113 cl6 p-b-26" style="
    text-align: justify;
">
						Ban đầu các cửa hàng bán đồ da, được thành lập vào năm 1913 bởi Mario Blizzard và anh trai Martino tại Milan, Ý.

						Mario Prada không tin rằng phụ nữ có thể kinh doanh do đó ông ngăn cản việc các người phụ nữ trong gia đình tham gia vào công việc của công ty. Nhưng con trai ông không có tài kinh doanh nên người kế nghiệm của Prada là con gái của ông Luisa Prada và đã điều hành công ty trong vòng 20 năm. Con gái riêng của Luisa, Miuccia Blizzard vào làm cho Blizzard và thay thế vị trí của mẹ mình vào năm 1978.

						Miuccia gặp Patrizio Bertelli vào năm 1977 một người Ý làm trong lĩnh vực kinh doanh đồ da ở tuổi 17, sau đó ông cũng gia nhập công ty. Ông là người đã đưa ra lời khuyên với Miuccia nên dừng nhập khẩu da từ anh và thay đổi phong cách hiện có.
					</p>


				</div>
			</div>

			<div class="col-11 col-md-5 col-lg-4 m-lr-auto">
				<div class="how-bor1 ">
					<div class="hov-img0">
						<img src="~/Asserts/images/Bowen-2017-Fall-Winter-Campaign-004.jpg" alt="IMG">
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="order-md-2 col-md-7 col-lg-8 p-b-30">
				<div class="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
					<h3 class="mtext-111 cl2 p-b-16">Sứ mệnh của Blizzard</h3>

					<p class="stext-113 cl6 p-b-26">
						Miuccia thừa kế công ty vào năm 1978 lúc đó doanh số bán hàng đã lên đến 450.000 USD. Cùng với Bertelli làm quản lý kinh doanh, Miuccia đã cho những ý tưởng của mình vào trong các bộ sưu tập của hãng. Bà cho ra đời bộ sưu tập của mình gồm có balo và túi xách, nó không được thành công như mong đợi do quảng cáo ít và có giá quá cao, nhưng đây cũng có thể coi là những bước đầu trong sự thành công trong thương mại của hãng về sau này.

						Sau đó, Miuccia và Bertelli tìm ra các địa chỉ bán buôn cho túi xách trong các của hàng bách hóa cao cấp và các cửa hàng thời trang trên thế giới. Vào năm 1983, Prada mở cửa hàng thứ hai tại Milan, cửa hàng này được đặt trong khu Galleria Vittorio Emanuele II.

					</p>

					<div class="bor16 p-l-29 p-b-9 m-t-22">
						<p class="stext-114 cl6 p-r-40 p-b-11" style="
    text-align: justify;
">

							Sáng tạo là thứ kết nối mọi thứ. Khi bạn hỏi một người có óc sáng tạo làm một điều gì đó, học nói rằng họ thấy một thứ. Nó trong có vẻ càng lúc càng rõ ràng
						</p>

						<span class="stext-111 cl8">
							- Steve Job’s
						</span>
					</div>
				</div>
			</div>

			<div class="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
				<div class="how-bor2">
					<div class="hov-img0">
						<img src="~/Asserts/images/schoen_mag_01_by_sandro_baebler.jpg" alt="IMG">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

trangwebbanhangasp/trangwebbanhangasp/Views/Home/Timkiem.cshtml
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/Asserts/automenu/jquery-ui.css" rel="stylesheet" />
<script src="~/Asserts/automenu/jquery-ui.js"></script>

@using (Html.BeginForm("Trangtimkiem", "Timkiem", FormMethod.Post))
{
	<div class="" style="display: block;">
		<div class="bor8 dis-flex p-l-15">
			<button class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04" style="height: 40px;">
				<i class="zmdi zmdi-search"></i>
			</button>
			<div style="border: none; padding-top: 4px;">
				@Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "form-control", @id = "searchInput", @style = "border:none;", @placeholder = "Tìm kiếm sản phẩm" })
			</div>

		</div>
	</div>
}
<script>
		$("#searchInput").autocomplete({
			source: function (request, response) {
				$.ajax({
					url: '@Url.Action("GetSearchValue","Home")',
					dataType: "json",
					data: { search: $("#searchInput").val() },
					success: function (data) {
						response($.map(data, function (item) {
							return { label: item.ten_sp, value: item.ten_sp };
						}));
					},
					error: function (xhr, status, error) {
						alert("Error");
					}
				});
			}
		});
</script>